[project]
name = "preprocessor"
version = "0.1.0"
description = "Preprocessor for raw Sanskrit text to prepare it for BPE tokenization."
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
